# Generated by Django 5.2.4 on 2026-03-10 06:45

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('OPTIMAL_TIMING', 'Optimal Timing'), ('BURNOUT_PREVENTION', 'Burnout Prevention'), ('TEAM_COORDINATION', 'Team Coordination'), ('WORKLOAD_BALANCE', 'Workload Balance'), ('WELLNESS', 'Wellness Recommendation')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('recommended_start_date', models.DateField()),
                ('recommended_end_date', models.DateField()),
                ('recommended_duration', models.PositiveIntegerField(help_text='Recommended leave duration in days')),
                ('reasoning', models.TextField(help_text='AI reasoning for this recommendation')),
                ('benefits', models.JSONField(default=list, help_text='List of expected benefits from taking this leave')),
                ('risk_factors', models.JSONField(default=list, help_text='Potential risk factors if leave is not taken')),
                ('current_workload_score', models.FloatField(default=0.5, help_text='Current workload intensity (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('burnout_risk_score', models.FloatField(default=0.0, help_text='Risk of burnout (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('team_impact_score', models.FloatField(default=0.5, help_text='Impact on team if leave is taken (lower is better)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('alternative_dates', models.JSONField(default=list, help_text='Alternative date ranges for the leave')),
                ('is_active', models.BooleanField(default=True)),
                ('was_acted_upon', models.BooleanField(default=False)),
                ('employee_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='AttendancePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('DAILY', 'Daily Prediction'), ('WEEKLY', 'Weekly Prediction'), ('MONTHLY', 'Monthly Prediction')], default='DAILY', max_length=10)),
                ('prediction_date', models.DateField()),
                ('attendance_probability', models.FloatField(help_text='Probability of attendance (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('lateness_probability', models.FloatField(help_text='Probability of being late (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('absence_risk', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='LOW', max_length=10)),
                ('contributing_factors', models.JSONField(default=dict, help_text='Factors contributing to the prediction (historical patterns, seasonality, etc.)')),
                ('model_confidence', models.FloatField(default=0.7, help_text='Confidence level of the AI model', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-prediction_date', 'employee'],
                'unique_together': {('employee', 'prediction_type', 'prediction_date')},
            },
        ),
        migrations.CreateModel(
            name='MoodAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(default=datetime.date.today)),
                ('mood_score', models.FloatField(help_text='Overall mood score from -1 (very negative) to 1 (very positive)', validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('mood_category', models.CharField(choices=[('VERY_NEGATIVE', 'Very Negative'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('POSITIVE', 'Positive'), ('VERY_POSITIVE', 'Very Positive')], max_length=15)),
                ('stress_level', models.FloatField(help_text='Stress level from 0 (no stress) to 1 (high stress)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('engagement_level', models.FloatField(help_text='Engagement level from 0 (disengaged) to 1 (highly engaged)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('satisfaction_level', models.FloatField(help_text='Job satisfaction from 0 (unsatisfied) to 1 (highly satisfied)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('data_sources', models.JSONField(default=list, help_text='List of data sources used for analysis')),
                ('analysis_factors', models.JSONField(default=dict, help_text='Detailed breakdown of factors affecting mood')),
                ('recommendations', models.TextField(blank=True, help_text='AI-generated recommendations for mood improvement')),
                ('requires_attention', models.BooleanField(default=False)),
                ('attention_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-analysis_date', 'employee'],
                'unique_together': {('employee', 'analysis_date')},
            },
        ),
    ]
